<?php 
// darle formato en español a nuestras fechas
$sqlF = mainModelo::conexion()->prepare("SET GLOBAL lc_time_names = 'es_ES'");
$sqlF -> execute();
$sql = mainModelo::conexion()->prepare("SELECT monto, DATE_FORMAT(fecha, '%d de %b %Y') as fecha FROM pagos_detalles WHERE pagos_id =:id");
$sql->bindParam(':id',$id);
....
....
....
....



